#!/bin/bash


echo 'Now the auto GPIO config for PRU0 and PRU1 starts'

#PRU0 is used for output
echo 'PRU0 p2.24:'
config-pin -a p2.24 pruout
config-pin -q p2.24

#PRU1 is used for input
echo 'PRU1 p1.04:'
config-pin -a p1.04 pruin
config-pin -q p1.04


